/*
 * keys.h
 *
 *  Created on: 23 Apr 2025
 *      Author: jondurrant
 */

#ifndef EXP_LEDCONTROLHTTPS_SRC_KEYS_H_
#define EXP_LEDCONTROLHTTPS_SRC_KEYS_H_

const char *s_tls_ca =
"-----BEGIN CERTIFICATE-----"
"MIIBkDCCATWgAwIBAgIUNglF3uKkxCEBE1Wwg3szSnVuVrowCgYIKoZIzj0EAwIw"
"HTEbMBkGA1UEAwwSdGVzdC5kcmpvbmVhLmNvLnVrMB4XDTI1MDUxNDA4MTE1MFoX"
"DTM1MDUxMjA4MTE1MFowHTEbMBkGA1UEAwwSdGVzdC5kcmpvbmVhLmNvLnVrMFkw"
"EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEYE8q6xCRzxNjq62TPPjVCxtYvmbNb275"
"ZZCsnhzPxUOWA4h9LYaTtPwCC2xfcFLQKZvSnecPgLG3YWgwYJHWE6NTMFEwHQYD"
"VR0OBBYEFKPAti1F09bAM4Fx+9ABUVGNlD6HMB8GA1UdIwQYMBaAFKPAti1F09bA"
"M4Fx+9ABUVGNlD6HMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIh"
"AMeDhxwYaYp+zxjqOf/ImzYa1ku1jbgYt3sF0Bi1qnRJAiEA3AllOrbDM3e7zHjB"
"pC1x1L9xEivZ0RZdYdBgVKYpXIE="
"-----END CERTIFICATE-----";

const char *s_tls_cert =
"-----BEGIN CERTIFICATE-----"
"MIIBhzCCAS6gAwIBAgIUFTXaVGYz+BVAQD6IZMkRetQ/OV4wCgYIKoZIzj0EAwIw"
"HTEbMBkGA1UEAwwSdGVzdC5kcmpvbmVhLmNvLnVrMB4XDTI1MDUxNDA4MTE1MFoX"
"DTM1MDUxMjA4MTE1MFowETEPMA0GA1UEAwwGY2xpZW50MFkwEwYHKoZIzj0CAQYI"
"KoZIzj0DAQcDQgAE4sCytcv9iplTauBNr4TVW2pxEzfS9vxXpK9rZ2OSyHAvTPWx"
"PavDI4Nf42HFLCn4KLy8dr6SgY08h9ZFGWfQ/6NYMFYwFAYDVR0RBA0wC4IJbG9j"
"YWxob3N0MB0GA1UdDgQWBBRpFiIwCuClZfaCWrs+k3tOvM+/XjAfBgNVHSMEGDAW"
"gBSjwLYtRdPWwDOBcfvQAVFRjZQ+hzAKBggqhkjOPQQDAgNHADBEAiBOdVizrNf+"
"8J1Wd3fD8/1CbR1TEPwd8vdjwSjwvQl1ugIgCpzCXcLwdBFnqVxzuq0jGVyofmWK"
"mUwc2eE6igGCgDA="
"-----END CERTIFICATE-----";


const char *s_tls_key =
"-----BEGIN EC PRIVATE KEY-----"
"MHcCAQEEIP5NBYjkEB8RkzIB/W5kI8tBGJHtmWWaF7H5hJoV6kP7oAoGCCqGSM49"
"AwEHoUQDQgAE4sCytcv9iplTauBNr4TVW2pxEzfS9vxXpK9rZ2OSyHAvTPWxPavD"
"I4Nf42HFLCn4KLy8dr6SgY08h9ZFGWfQ/w=="
"-----END EC PRIVATE KEY-----" ;

#endif /* EXP_LEDCONTROLHTTPS_SRC_KEYS_H_ */"
